# Generated by Django 4.1.3 on 2022-12-01 20:48

from django.db import migrations, models
import django.utils.timezone
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=main.utils.get_user_default_profile_image, null=True, upload_to=main.utils.get_profile_image_filepath),
        ),
    ]
