# Generated by Django 4.1.3 on 2022-12-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_managers_customuser_data_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodels',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
